# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# orbs: 
#   python3: circleci/python:3.7-alpine3.11

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["55:a8:e8:6a:0d:d1:ee:57:e9:0b:8a:c6:95:db:a0:09"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml

workflows:
  config_workflow:
    jobs:
      - configure_infrastructure
